ems:
  enabled: true
  servers:
    -
      server: localhost
      port: 7222
      user: user
      password: password

    -
      server: localhost
      port: 7222
      user: user
      password: password

    -
      server: localhost
      port: 7222
      user: user
      password: password

  queue: test.queue
  listener:
      enabled: false